# TYPE  DATABASE        USER            ADDRESS             METHOD
# Unix socket (локално унутар контејнера)
local   all             all                                 trust

# Локалхост (ако приступаш са хоста преко 127.0.0.1)
host    all             all             127.0.0.1/32        scram-sha-256
host    all             all             ::1/128             scram-sha-256

# Docker бридж мрежа (примерно 172.16.0.0/12; можеш сузити на твој subnet)
host    all             all             172.16.0.0/12       scram-sha-256
