hibernate.dialect=net.datenwerke.rs.utils.hibernate.PostgreSQLDialect
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://pg:5432/reportserver
hibernate.connection.username=reportserver
hibernate.connection.password=reportserver
hibernate.connection.autocommit=false
