# Директоријум за Lucene индекс
rs.lucene.dir=/lucene_index

# (опционо) Базни URL — прилагодити по потреби
rs.baseurl=http://localhost:8085/reportserver

# (опционо) број scheduler нити
rs.scheduleThreads=2

# (опционо) директоријум за логове (Tomcat)
logging.dir=/usr/local/tomcat/logs
